<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Customer_model extends CI_Model
{

    public $table = 'customer';
    public $id = 'CustomerID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_new_today()
    {
        $this->db->where(" created_at LIKE '".date('Y-m-d')."%"."' ");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('CustomerID', $q);
	$this->db->or_like('Firstname', $q);
	$this->db->or_like('Lastname', $q);
	$this->db->or_like('Address', $q);
	$this->db->or_like('MobilePhone', $q);
	$this->db->or_like('Email', $q);
	$this->db->or_like('Username', $q);
	$this->db->or_like('Password', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('CustomerID', $q);
	$this->db->or_like('Firstname', $q);
	$this->db->or_like('Lastname', $q);
	$this->db->or_like('Address', $q);
	$this->db->or_like('MobilePhone', $q);
	$this->db->or_like('Email', $q);
	$this->db->or_like('Username', $q);
	$this->db->or_like('Password', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Customer_model.php */
/* Location: ./application/models/Customer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-13 18:56:48 */
/* http://harviacode.com */