<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Order_model extends CI_Model
{

    public $table = 'order';
    public $id = 'OrderID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_latest_all()
    {
        $this->db->order_by('OrderDate', 'DESC');
        return $this->db->get($this->table)->result();
    }

    function get_all_by_client($ClientID)
    {
        $this->db->where(array('CustomerID'=>$ClientID));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_join_product()
    {
        $this->db->select(' SUM(shoppingbag.amount) as sum_amount, SUM(shoppingbag.totalprice) as sum_totalprice ');
        $this->db->join('shoppingbag', 'shoppingbag.OrderID = order.OrderID');
        // $this->db->group_by('');
        // $this->db->join('product', 'shoppingbag.ProductID = product.ProductID');
        return $this->db->get($this->table)->result();
    }

    function get_all_complete()
    {
        $this->db->where(array('OrderStatus'=>'complete'));
        return $this->db->get($this->table)->result();
    }

    function get_all_ordering()
    {
        $this->db->where(array('OrderStatus'=>'ordering'));
        return $this->db->get($this->table)->result();
    }

    function get_all_ordering_by_client($ClientID){
        $this->db->where(array(
            'CustomerID'=>$ClientID ,
            'OrderStatus'=>'ordering'
            ));
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function count_all_wait_confirm(){
        $this->db->where(array(
            'OrderStatus'=>'wait_confirm'
            ));
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('OrderID', $q);
	$this->db->or_like('OrderDate', $q);
	$this->db->or_like('OrderStatus', $q);
	$this->db->or_like('CustomerID', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('OrderID', $q);
	$this->db->or_like('OrderDate', $q);
	$this->db->or_like('OrderStatus', $q);
	$this->db->or_like('CustomerID', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);

        $id = $this->db->insert_id();
        $q = $this->db->get_where($this->table, array('OrderID'=>$id));
        return $q->row();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Order_model.php */
/* Location: ./application/models/Order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-13 18:56:55 */
/* http://harviacode.com */