<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Payment_model extends CI_Model
{

    public $table = 'payment';
    public $id = 'PaymentID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('PaymentID', $q);
	$this->db->or_like('PaymentDate', $q);
	$this->db->or_like('TotalPrice', $q);
	$this->db->or_like('OrderID', $q);
	$this->db->or_like('PhoneNum', $q);
	$this->db->or_like('bank', $q);
    $this->db->or_like('ImagePath', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('PaymentID', $q);
	$this->db->or_like('PaymentDate', $q);
	$this->db->or_like('TotalPrice', $q);
	$this->db->or_like('OrderID', $q);
	$this->db->or_like('PhoneNum', $q);
	$this->db->or_like('bank', $q);
    $this->db->or_like('ImagePath', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

        // get data with limit and search
        function get_limit_data_wait_confirm($limit, $start = 0, $q = NULL) {

            $this->db->join('order', 'order.OrderID = payment.OrderID');            
            $this->db->order_by($this->id, $this->order);
            $this->db->where('OrderStatus', 'wait_confirm');            
            $this->db->group_start();
            $this->db->like('PaymentID', $q);
            $this->db->or_like('PaymentDate', $q);
            $this->db->or_like('TotalPrice', $q);
            $this->db->or_like('payment.OrderID', $q);
            $this->db->or_like('PhoneNum', $q);
            $this->db->or_like('bank', $q);
            $this->db->or_like('ImagePath', $q);
            $this->db->group_end();
            $this->db->limit($limit, $start);

            return $this->db->get($this->table)->result();
        }

            // get total rows wait_confirm
    function total_rows_wait_confirm($q = NULL) {
        $this->db->join('order', 'order.OrderID = payment.OrderID');            
        $this->db->where('OrderStatus', 'wait_confirm');            
        $this->db->group_start();
        $this->db->like('PaymentID', $q);
        $this->db->or_like('PaymentDate', $q);
        $this->db->or_like('TotalPrice', $q);
        $this->db->or_like('payment.OrderID', $q);
        $this->db->or_like('PhoneNum', $q);
        $this->db->or_like('bank', $q);
        $this->db->or_like('ImagePath', $q);
        $this->db->group_end();
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Payment_model.php */
/* Location: ./application/models/Payment_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-17 14:50:05 */
/* http://harviacode.com */