<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Promotion_model extends CI_Model
{

    public $table = 'promotion';
    public $id = 'PromotionID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_active()
    {
        $today = date('Y-m-d');
        $this->db->where('StartDate <=', $today);
        $this->db->or_where('EndDate >=', $today);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('PromotionID', $q);
	$this->db->or_like('StartDate', $q);
	$this->db->or_like('EndDate', $q);
	$this->db->or_like('PromotionDetail', $q);
	$this->db->or_like('PromotionName', $q);
	$this->db->or_like('UnitOfDiscount', $q);
	$this->db->or_like('TypePromotion', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('PromotionID', $q);
	$this->db->or_like('StartDate', $q);
	$this->db->or_like('EndDate', $q);
	$this->db->or_like('PromotionDetail', $q);
	$this->db->or_like('PromotionName', $q);
	$this->db->or_like('UnitOfDiscount', $q);
	$this->db->or_like('TypePromotion', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        $insert_id = $this->db->insert_id();
        
        return  $insert_id;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Promotion_model.php */
/* Location: ./application/models/Promotion_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-02 15:50:56 */
/* http://harviacode.com */