<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Shoppingbag_model extends CI_Model
{

    public $table = 'shoppingbag';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function is_item_in_cart($ProductID, $CustomerID){
        $this->db->where('CustomerID', $CustomerID);
        $this->db->where('ProductID', $ProductID);
        $this->db->where('OrderID IS NULL', null, false);
        $this->db->from($this->table);

        if($this->db->count_all_results()>0)
            return true;

        return false;
    }

    function get_user_cart_all($CustomerID){
        $this->db->where('CustomerID', $CustomerID);
        $this->db->where('OrderID IS NULL', null, false);
        // $this->db->from($this->table);
        return $this->db->get($this->table)->result();
    }

    function get_user_unordered_cart($CustomerID){
        $this->db->where('CustomerID', $CustomerID);
        $this->db->where(array('OrderID'=>NULL));
        // $this->db->from($this->table);
        return $this->db->get($this->table)->result();
    }

    function get_user_unordered_cart_all($CustomerID){
        $this->db->where('CustomerID', $CustomerID);
        $this->db->where(array('OrderID'=>NULL));
        $this->db->from($this->table);

        $countAll = $this->db->count_all_results();
        if($countAll>0)
            return $countAll;

        return null;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('CustomerID', $q);
	$this->db->or_like('ProductID', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('totalprice', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('CustomerID', $q);
	$this->db->or_like('ProductID', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('totalprice', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function deleteAllPromotion($PromotionID, $CustomerID){
        $this->db->where("PromotionID", $PromotionID);
        $this->db->where("CustomerID", $CustomerID);
        $this->db->delete($this->table);
    }

}

/* End of file Shoppingbag_model.php */
/* Location: ./application/models/Shoppingbag_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-03-28 14:48:09 */
/* http://harviacode.com */